#! /bin/bash
T=temp_include
F=temp_file

for f in *.mdt; do
  cat $f > $T
  while grep -q '%include' $T; do
    line=`grep -n '%include' $T | head -1 | sed -e 's/:.*//'`
    file=`grep '%include' $T | head -1 | sed -e 's/%include *//'`
    cat $file | sed -e "s^\\\$\@^$file^" > $F
    linem=$(expr $line - 1)
    linep=$(expr $line + 1)
    head -$linem $T > begin
    tail +$linep $T > rest
    cat begin $F rest > $T
    rm begin rest $F
  done
  modtime=$(date -r $f "+%Y-%m-%d %H:%M:%S")
  sed -i -e "s/LAST_MODIFIED/_Last modified: ${modtime}_/" $T

  mdfile=`echo $f | sed -e s/mdt/md/`
  if diff -q $T $mdfile > /dev/null; then
    ##echo $mdfile unchanged
    rm $T
  else
    mv $T $mdfile
    echo $mdfile updated
  fi

done
