#! /bin/bash
T=temp_include
F=temp_file

./checklinks

for f in *.md ; do
  grep -e "^title: JML Tutorial - " $f > /dev/null || echo $f has incorrect title line
  if [ `grep -e '^---$' $f | wc -l` != "2" ] ; then echo "$f does not have two --- lines" ; fi
  egrep -e 'TBD|TODO' $f  > /dev/null &&  echo "$f has TBD or TODO markings" 
done

