#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"

rm -rf A.class
X=0
openjml --rac --rac-compile-to-java-assert A.java
openjml-java -ea A |& diff out1.txt - || X=1

openjml --rac --no-rac-compile-to-java-assert A.java
openjml-java A |& diff out2.txt - || X=1

rm -rf A.class
exit $X
