#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"

rm -rf A.class
X=0
openjml --rac --rac-java-checks A.java
openjml-java A |& diff out1.txt - || X=1

openjml --rac --no-rac-java-checks A.java
openjml-java A |& diff out2.txt - || X=1

rm -rf A.class
exit $X
