#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"

rm -rf Demo.class
X=0
openjml --rac --rac-check-assumptions Demo.java
( ( openjml-java Demo |& tee actual | diff RAC.out - ) && rm -rf actual) || X=1

rm -rf Demo.class
exit $X
