#! /usr/bin/env bash

D=$(dirname "$BASH_SOURCE"); cd "$D"
rm -rf A.class

X=0
openjml --rac --rac-show-source=source A.java
openjml-java A | diff out1.txt - || X=1

openjml --rac --rac-show-source=line A.java
openjml-java A | diff out2.txt - || X=1

openjml --rac --rac-show-source=none A.java
openjml-java A | diff out3.txt - || X=1

rm -rf A.class
exit $X
